### ISSUE TITLE
Logging of httpserver events?

### ISSUE THREAD

**Issue by mskyttner** [quackscience/duckdb-extension-httpserver#16]
I run a container which has this (superneat) extension installed and wonder if there is any logging available?

Currently I'm starting the service using this (compose.yaml):

```yaml
services:
  duckserve:
    image: duckserve
    command: bash -c "DUCKDB_HTTPSERVER_FOREGROUND=1 duckdb -init serve.sql"
    volumes:
      - ./serve.sql:/serve.sql:ro
    ports:
      - "9999:9999"
```

The `serve.sql` init script I'm testing this setup with has various statements and end with: `select httpserve_start('0.0.0.0', 9999, '');` ... 

The service runs fine and is fast, and now I wonder if log messages can made visible to the container? Written to some kind of stream or to an in-memory duckdb table like 'httpserver_log' or both?

Thankful for any ideas/hints!
